# Generated by Django 3.1.6 on 2021-08-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FORPWD', '0002_auto_20210824_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='cashgift',
            new_name='cash',
        ),
    ]
