# Generated by Django 3.1.6 on 2021-08-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORPWD', '0003_auto_20210824_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='cash',
            field=models.CharField(choices=[('Received', 'received'), ('', '')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='gift',
        ),
    ]
