# Generated by Django 3.1.6 on 2021-08-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORPWD', '0007_auto_20210824_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='cash',
            field=models.CharField(choices=[('Received', 'received'), ('', '')], default='Blank', max_length=100, null=True),
        ),
    ]
